# Default values for jenkins.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

maintainers:
  name: Mikalai.Lukyanchyk
  email: Mikalai.Lukyanchyk@gmail.com

# ReplicaSet
replicaCount: 1

# Image with tag
image:
  repository: lukyanchyk/project-sa
  pullPolicy: IfNotPresent
  tag: "50"

# Service port configurations
service:
  ports:
    http: 80

# Resource for pod (with different notation)
resources:
  requests:
    cpu: 100m
    memory: 200Mi
  limits:
    cpu: 1
    memory: 1Gi

# Ingress configurations
ingress:
  ingressClass: nginx
  host: wp-project.k8s-12.sa

wpdbEnvs:
  - name: WORDPRESS_DB_HOST
    value: 192.168.201.12:3306
  - name: WORDPRESS_DB_NAME
    value: wordpress
  - name: WORDPRESS_DB_USER
    value: db_wp_admin
  - name: WORDPRESS_DB_PASSWORD
    value: db_wp_admin

storageClass:
  onDelete: retain
  pathPattern: v0.6.0