replicaCount: 2

image:
  repository: lukyanchyk/test-deploy
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wordpress-pr.k8s-12.sa

persistentVolumeClaim:
  storageSize: 8Gi

env:
  - name: WORDPRESS_DB_HOST
    value: 192.168.203.22
  - name: WORDPRESS_DB_NAME
    value: db_wordpress
  - name: WORDPRESS_DB_USER
    value: us_wordpress
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress
  - name: WP_DEBUG_LOG
    value: wordpress