replicaCount: 2

image:
  repository: lukyanchyk/project-sa
  # Overrides the image tag whose default is the chart appVersion.
  tag: "50"

service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wordpress.k8s-12.sa

persistentVolumeClaim:
  storageSize: 8Gi

ip_server: 192.168.37.105
nfs_mount: /mnt/IT-Academy/nfs-data/sa2-23-23/Mikalai.Lukyanchyk/wordpress

env:
  - name: WORDPRESS_DB_HOST
    value: 192.168.201.12
  - name: WORDPRESS_DB_NAME
    value: wordpress
  - name: WORDPRESS_DB_USER
    value: db_wp_admin
  - name: WORDPRESS_DB_PASSWORD
    value: db_wp_admin
  - name: WP_DEBUG_LOG
    value: wordpress

resources:
  limits:
    cpu: 3000m
    memory: 3000Mi
  requests:
    cpu: 2000m
    memory: 2000Mi