apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sa-wordpress
  namespace: default
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistentVolumeClaim.storageSize }}
  selector:
    matchLabels:
      name: wordpress-nfs-vol
      type: nfs